name: Java CI with Gradle

on:
  push:
    branches:
      - main

jobs:
  build:
    
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # 根据您的项目需求选择合适的JDK版本  
          distribution: 'temurin'  # 或者选择其他JDK分发版，如'zulu'、'adopt'等  

      - name: Build with Gradle
        run: ./gradlew.bat build
        shell: cmd  # 指定使用CMD shell来运行命令  


      - name: Test with Gradle
        run: ./gradlew.bat test
        shell: cmd  # 指定使用CMD shell来运行命令

